### PR TITLE
Change CI runner from Ubuntu 18.04 to ubuntu-latest

### PR DESCRIPTION
**Pull request by kjsanger**

### CODE REVIEW

**Comment by mksanger** [comment]
Apparently the workflow didn'r run for the most recent commit, and I can't see why, which is slightly worrying

**Comment by kjsanger** [comment]
There was a run after the update to baton 4.0.0. I've manually triggered a re-run anyway

**Comment by mksanger** [comment]
This is confusing to me, because I still only see the "successful tests run" tick mark next to 805bcaf

**Comment by mksanger** [comment]
Never mind, I see that it did install baton 4.0.0, just github being strange

**Pull request merged**
